import type { CanvasNode, CanvasState, EntityField } from './types.js'
import { canvasToPrisma } from './prisma.js'

type Entity = CanvasNode & { data: { name: string; fields: EntityField[] } }
type Endpoint = CanvasNode & {
  data: { name: string; method: string; path: string; handler?: string; auth?: boolean }
}
type Job = CanvasNode & {
  data: { name: string; kind: 'cron' | 'queue'; schedule?: string; queue?: string; handler?: string }
}
type Machine = CanvasNode & {
  data: {
    name: string
    initial: string
    states: string[]
    transitions: Array<{ from: string; to: string; event: string }>
  }
}
type Service = CanvasNode & { data: { name: string; kind: string } }

const isEntity = (n: CanvasNode): n is Entity =>
  n.type === 'entity' && Array.isArray((n.data as { fields?: unknown }).fields)
const isEndpoint = (n: CanvasNode): n is Endpoint => n.type === 'endpoint'
const isJob = (n: CanvasNode): n is Job => n.type === 'job'
const isMachine = (n: CanvasNode): n is Machine => n.type === 'state_machine'
const isService = (n: CanvasNode): n is Service => n.type === 'service'

function lower(s: string): string {
  return s.length ? s[0]!.toLowerCase() + s.slice(1) : s
}

function indent(block: string, spaces: number): string {
  const pad = ' '.repeat(spaces)
  return block
    .split('\n')
    .map((line) => (line.length ? pad + line : line))
    .join('\n')
}

export function canvasToRoutes(state: CanvasState): string {
  const endpoints = state.nodes.filter(isEndpoint)
  const entities = state.nodes.filter(isEntity)

  const out: string[] = []
  out.push('// Generated by supabackend canvas. Edit the canvas, not this file.')
  out.push("import { Router } from 'express'")
  out.push("import { PrismaClient } from '@prisma/client'")
  out.push('')
  out.push('export const router = Router()')
  out.push('const prisma = new PrismaClient()')
  out.push('')

  if (!endpoints.length) {
    out.push('// No endpoints defined on the canvas.')
    return out.join('\n') + '\n'
  }

  for (const ep of endpoints) {
    const method = (ep.data.method ?? 'GET').toLowerCase()
    const path = ep.data.path ?? '/'

    const reads = state.edges
      .filter((e) => e.source === ep.id && e.data?.kind === 'reads')
      .map((e) => entities.find((ent) => ent.id === e.target))
      .filter((e): e is Entity => !!e)
    const writes = state.edges
      .filter((e) => e.source === ep.id && e.data?.kind === 'writes')
      .map((e) => entities.find((ent) => ent.id === e.target))
      .filter((e): e is Entity => !!e)

    out.push(`// ${method.toUpperCase()} ${path} — canvas node: ${ep.id}`)
    out.push(`router.${method}('${path}', async (req, res) => {`)
    if (ep.data.auth) out.push('  // TODO: auth required')
    out.push('  try {')

    if (ep.data.handler) {
      out.push(indent(ep.data.handler, 4))
    } else {
      out.push(indent(autoStub(method, path, reads, writes, ep.data.name), 4))
    }

    out.push('  } catch (err) {')
    out.push(`    console.error('[${method.toUpperCase()} ${path}]', err)`)
    out.push('    res.status(500).json({ error: (err as Error).message })')
    out.push('  }')
    out.push('})')
    out.push('')
  }

  return out.join('\n')
}

function autoStub(
  method: string,
  path: string,
  reads: Entity[],
  writes: Entity[],
  fallbackName: string,
): string {
  if (method === 'get' && reads.length) {
    const model = lower(reads[0]!.data.name)
    if (path.includes(':id')) {
      return [
        `const ${model} = await prisma.${model}.findUnique({ where: { id: req.params.id } })`,
        `if (!${model}) return res.status(404).json({ error: 'not found' })`,
        `res.json(${model})`,
      ].join('\n')
    }
    return [
      `const items = await prisma.${model}.findMany()`,
      `res.json(items)`,
    ].join('\n')
  }
  if (method === 'post' && writes.length) {
    const model = lower(writes[0]!.data.name)
    return [
      `const created = await prisma.${model}.create({ data: req.body })`,
      `res.status(201).json(created)`,
    ].join('\n')
  }
  if ((method === 'put' || method === 'patch') && writes.length) {
    const model = lower(writes[0]!.data.name)
    return [
      `const updated = await prisma.${model}.update({`,
      `  where: { id: req.params.id },`,
      `  data: req.body,`,
      `})`,
      `res.json(updated)`,
    ].join('\n')
  }
  if (method === 'delete' && writes.length) {
    const model = lower(writes[0]!.data.name)
    return [
      `await prisma.${model}.delete({ where: { id: req.params.id } })`,
      `res.status(204).send()`,
    ].join('\n')
  }
  return `res.json({ message: 'TODO: implement ${fallbackName}' })`
}

export function canvasToJobs(state: CanvasState): string {
  const jobs = state.nodes.filter(isJob)
  const hasCron = jobs.some((j) => j.data.kind === 'cron')
  const hasQueue = jobs.some((j) => j.data.kind === 'queue')

  const out: string[] = []
  out.push('// Generated by supabackend canvas. Edit the canvas, not this file.')
  if (hasCron) out.push("import { CronJob } from 'cron'")
  if (hasQueue) out.push("import { Worker } from 'bullmq'")
  out.push("import { PrismaClient } from '@prisma/client'")
  out.push('')
  out.push('const prisma = new PrismaClient()')
  out.push('')

  if (!jobs.length) {
    out.push('export function startJobs() {}')
    return out.join('\n') + '\n'
  }

  out.push('export function startJobs() {')
  for (const job of jobs) {
    const name = job.data.name
    out.push(`  // ${name} — canvas node: ${job.id}`)
    if (job.data.kind === 'cron') {
      const schedule = job.data.schedule ?? '0 * * * *'
      out.push(`  new CronJob('${schedule}', async () => {`)
      const body = job.data.handler ?? `console.log('[cron] ${name} tick')`
      out.push(indent(body, 4))
      out.push('  }).start()')
    } else {
      const queue = job.data.queue ?? name
      out.push(`  new Worker('${queue}', async (job) => {`)
      const body = job.data.handler ?? `console.log('[worker] ${name}', job.data)`
      out.push(indent(body, 4))
      out.push(`  }, { connection: { host: 'localhost', port: 6379 } })`)
    }
    out.push('')
  }
  out.push('}')

  return out.join('\n') + '\n'
}

export function canvasToMachines(state: CanvasState): string {
  const machines = state.nodes.filter(isMachine)

  const out: string[] = []
  out.push('// Generated by supabackend canvas. Edit the canvas, not this file.')
  if (!machines.length) return out.join('\n') + '\n'

  out.push("import { createMachine } from 'xstate'")
  out.push('')

  for (const m of machines) {
    const name = m.data.name
    const states = m.data.states ?? []
    const transitions = m.data.transitions ?? []
    const initial = m.data.initial ?? states[0] ?? 'start'

    out.push(`// ${name} — canvas node: ${m.id}`)
    out.push(`export const ${name}Machine = createMachine({`)
    out.push(`  id: '${name}',`)
    out.push(`  initial: '${initial}',`)
    out.push('  states: {')
    for (const s of states) {
      const outgoing = transitions.filter((t) => t.from === s)
      if (outgoing.length) {
        out.push(`    ${s}: {`)
        out.push('      on: {')
        for (const t of outgoing) {
          out.push(`        ${t.event}: '${t.to}',`)
        }
        out.push('      },')
        out.push('    },')
      } else {
        out.push(`    ${s}: { type: 'final' },`)
      }
    }
    out.push('  },')
    out.push('})')
    out.push('')
  }

  return out.join('\n')
}

export function canvasToCompose(state: CanvasState): string {
  const services = state.nodes.filter(isService)
  const entities = state.nodes.filter(isEntity)
  const jobs = state.nodes.filter(isJob)
  const hasQueue = jobs.some((j) => j.data.kind === 'queue')

  const out: string[] = []
  out.push('# Generated by supabackend canvas. Edit the canvas, not this file.')
  out.push('version: "3.9"')
  out.push('services:')

  for (const svc of services) {
    const name = svc.data.name
    const kind = svc.data.kind ?? 'http-service'
    out.push(`  ${name}:`)
    if (['postgres', 'database', 'db'].includes(kind)) {
      out.push('    image: postgres:16')
      out.push('    environment:')
      out.push('      POSTGRES_PASSWORD: dev')
      out.push('      POSTGRES_DB: app')
      out.push('    ports: ["5432:5432"]')
    } else if (kind === 'redis') {
      out.push('    image: redis:7')
      out.push('    ports: ["6379:6379"]')
    } else {
      out.push(`    build: ./${name}`)
      out.push('    ports: ["3000:3000"]')
    }
  }

  const hasDb = services.some((s) => ['postgres', 'database', 'db'].includes(s.data.kind ?? ''))
  if (entities.length && !hasDb) {
    out.push('  db:')
    out.push('    image: postgres:16')
    out.push('    environment:')
    out.push('      POSTGRES_PASSWORD: dev')
    out.push('      POSTGRES_DB: app')
    out.push('    ports: ["5432:5432"]')
  }

  const hasRedis = services.some((s) => s.data.kind === 'redis')
  if (hasQueue && !hasRedis) {
    out.push('  redis:')
    out.push('    image: redis:7')
    out.push('    ports: ["6379:6379"]')
  }

  return out.join('\n') + '\n'
}

function generateIndex(state: CanvasState): string {
  const hasEndpoints = state.nodes.some(isEndpoint)
  const hasJobs = state.nodes.some(isJob)
  const lines: string[] = [
    '// Generated by supabackend canvas.',
    "import express from 'express'",
  ]
  if (hasEndpoints) lines.push("import { router } from './routes.js'")
  if (hasJobs) lines.push("import { startJobs } from './jobs.js'")
  lines.push('')
  lines.push('const app = express()')
  lines.push('app.use(express.json())')
  if (hasEndpoints) lines.push('app.use(router)')
  lines.push('')
  if (hasJobs) lines.push('startJobs()')
  lines.push('')
  lines.push('const port = Number(process.env.PORT ?? 3000)')
  lines.push('app.listen(port, () => console.log(`server on :${port}`))')
  return lines.join('\n') + '\n'
}

function generatePackageJson(state: CanvasState): string {
  const jobs = state.nodes.filter(isJob)
  const hasCron = jobs.some((j) => j.data.kind === 'cron')
  const hasQueue = jobs.some((j) => j.data.kind === 'queue')
  const hasMachines = state.nodes.some(isMachine)

  const deps: Record<string, string> = {
    '@prisma/client': '^5.22.0',
    express: '^4.21.1',
  }
  if (hasCron) deps.cron = '^3.1.7'
  if (hasQueue) deps.bullmq = '^5.21.2'
  if (hasMachines) deps.xstate = '^5.19.0'

  const pkg = {
    name: 'supabackend-app',
    version: '0.1.0',
    type: 'module',
    scripts: {
      dev: 'tsx watch src/index.ts',
      build: 'tsc',
      start: 'node dist/index.js',
      'db:push': 'prisma db push',
    },
    dependencies: deps,
    devDependencies: {
      '@types/express': '^5.0.0',
      '@types/node': '^22.10.1',
      prisma: '^5.22.0',
      tsx: '^4.19.2',
      typescript: '^5.7.2',
    },
  }
  return JSON.stringify(pkg, null, 2) + '\n'
}

function generateTsconfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'bundler',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        outDir: 'dist',
      },
      include: ['src/**/*'],
    },
    null,
    2,
  ) + '\n'
}

function generateReadme(state: CanvasState): string {
  const counts: Record<string, number> = {}
  for (const n of state.nodes) counts[n.type] = (counts[n.type] ?? 0) + 1
  const lines: string[] = []
  lines.push('# supabackend-app')
  lines.push('')
  lines.push('Generated by the supabackend canvas. Layers:')
  lines.push('')
  for (const [k, v] of Object.entries(counts)) lines.push(`- **${k}**: ${v}`)
  lines.push('')
  lines.push('## Run')
  lines.push('')
  lines.push('```bash')
  lines.push('npm install')
  lines.push('docker compose up -d')
  lines.push('npx prisma db push')
  lines.push('npm run dev')
  lines.push('```')
  lines.push('')
  return lines.join('\n')
}

function generateEnvExample(): string {
  return 'DATABASE_URL=postgresql://postgres:dev@localhost:5432/app\n'
}

export function canvasToApp(state: CanvasState): Record<string, string> {
  const files: Record<string, string> = {}
  files['package.json'] = generatePackageJson(state)
  files['tsconfig.json'] = generateTsconfig()
  files['.env.example'] = generateEnvExample()
  files['README.md'] = generateReadme(state)
  files['docker-compose.yml'] = canvasToCompose(state)

  if (state.nodes.some(isEntity)) {
    files['prisma/schema.prisma'] = canvasToPrisma(state)
  }
  files['src/index.ts'] = generateIndex(state)
  if (state.nodes.some(isEndpoint)) files['src/routes.ts'] = canvasToRoutes(state)
  if (state.nodes.some(isJob)) files['src/jobs.ts'] = canvasToJobs(state)
  if (state.nodes.some(isMachine)) files['src/machines.ts'] = canvasToMachines(state)

  return files
}
